### ISSUE TITLE
Jupyter Releaser setup

### ISSUE THREAD

**Issue by jtpio** [QuantStack/yjs-widgets#17]
Keeping track of the list of tasks:

- [x] Create the GitHub app for the `QuantStack` org
- [x] Add workflows: https://github.com/QuantStack/yjs-widgets/pull/16
- [x] Create the `release` environment and add `APP_ID` and `APP_PRIVATE_KEY`
- [x] Add trusted publisher to the PyPI repo: https://pypi.org/project/yjs-widgets/
- [x] Add `NPM_TOKEN` to the secrets (org secret)
- [x] Make sure the npm package has a public publish config: https://jupyter-releaser.readthedocs.io/en/latest/faq/index.html#failed-to-publish-a-package-to-npm

https://github.com/QuantStack/yjs-widgets/blob/5010afdcec88fda5589b4ac677f3e952d40d815b/package.json#L94-L96

- [x] Add `quantstack-bot` as a contributor to the package on npm: https://www.npmjs.com/~quantstack-bot - https://www.npmjs.com/package/yjs-widgets
- [x] Init `CHANGELOG.md`: https://github.com/QuantStack/yjs-widgets/pull/18

**Comment by davidbrochart** [comment]
I just released [v0.3.8](https://github.com/QuantStack/yjs-widgets/releases/tag/v0.3.8) with the jupyter-releaser, thanks!
